services:
  db:
    image: postgres:latest
    container_name: postgres-exercise-public
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      -  postgres-exercise-public-data:/var/lib/postgresql/data

  media-server:
    build:
      context: ./media-server-public
    container_name: media_server_public
    ports:
      - "8081:80"
    volumes:
      - ./media:/usr/share/nginx/html/media
volumes:
  postgres-exercise-public-data:
    driver: local